### ISSUE TITLE
Feature request: Show SGB borders outside SGB mode.

### ISSUE THREAD

**Issue by neumaennl** [Steveice10/GameYob#35]
Hi,

I'm really glad Super GameBoy borders are working now!
Could you please add an option to also display the SGB border in GBC mode?
It would also be great to have prioritization options for custom vs. SGB borders, so that e.g. the SGB border is displayed if available and the custom border otherwise.
I also noted that with the current code the display does not refresh when custom borders are not switched on.

**Comment by krystal-starfox11111** [comment]
I can't get the Super GameBoy borders to work. I tried v1.0.8 in both 3DSX, & CIA. How did you get it working?

**Comment by neumaennl** [comment]
It's not in the latest release as the latest release is quite old. I built a CIA from source.

**Comment by mrTruch** [comment]
Excuse me, I don't know how to build a CIA from source can anyone explain or the author update it? Thanks.

**Comment by Steveice10** [comment]
I think I'm going to have to pass on this feature, since it involves a rather hacky workaround. If you really want the SGB borders in GBC mode, you could always find it online and load it as a custom border image file. There appears to be a fairly comprehensive collection of borders here: http://www.vgmuseum.com/features/sgb/
